yatube/about/urls.py
from about.views import AboutAuthorView, AboutTechView
from django.urls import path

app_name = 'about'

urlpatterns = [
    path('author/', AboutAuthorView.as_view(), name='author'),
    path('tech/', AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_list, name='group_list'),
    path('create/', views.post_create, name='post_create'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

yatube/posts/models.py
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    text = models.TextField(verbose_name='Текст статьи',
                            help_text='Введите текст статьи')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации',
                                    help_text='Укажите дату '
                                              'публикации')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='posts',
                               verbose_name='Автор статьи',
                               help_text='Укажите автора статьи')
    group = models.ForeignKey('Group', blank=True, null=True,
                              on_delete=models.SET_NULL,
                              related_name='posts',
                              verbose_name='Группа статей',
                              help_text='Выберите тематическую группу '
                                        'в выпадающем списке по желанию')

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название группы',
                             help_text='Введите название тематической группы')
    slug = models.SlugField(unique=True, verbose_name='Номер группы',
                            help_text='Укажите порядковый номер группы')
    description = models.TextField(verbose_name='Описание группы',
                                   help_text='Добавьте текст описания группы')

    class Meta:
        verbose_name = 'Группа статей'
        verbose_name_plural = 'Группы статей'
        ordering = ('-title',)

    def __str__(self):
        return self.title

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 7}),
            'group': forms.Select(attrs={'class': 'form-control'})
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Об авторе проекта'
        context['header'] = ('Привет, я автор')
        context['text'] = ('Тут я размещу информацию о себе используя '
                           'свои умения верстать. Картинки, блоки, элементы '
                           'бустрап. А может быть, просто напишу несколько '
                           'абзацев текста.')
        return context


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Технологии'
        context['header'] = ('Вот что я умею')
        context['text'] = ('Текст страницы "Технологии"')
        return context

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from posts.forms import PostForm
from posts.models import Group, Post

User = get_user_model()


def index(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'paginator': paginator,
    }
    return render(request, 'posts/index.html', context)


def profile(request, username):
    user_obj = get_object_or_404(User, username=username)
    posts = user_obj.posts.all()
    paginator = Paginator(posts, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'user_obj': user_obj,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post': post,
    }
    return render(request, 'posts/post_detail.html', context)


def group_list(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'paginator': paginator,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


@login_required
def post_create(request):
    form = PostForm(data=request.POST)

    if request.method != 'POST':
        form = PostForm()
        return render(request, 'posts/post_create.html', {'form': form})

    if not form.is_valid():
        return render(request, 'posts/post_create.html', {'form': form})

    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', post.author)


def post_edit(request, post_id):
    is_edit = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST, instance=is_edit)

    if is_edit.author != request.user:
        return redirect('posts:post_detail', post_id)

    if request.method != 'POST' or not form.is_valid():
        form = PostForm(instance=is_edit)
        return render(
            request,
            'posts/post_create.html',
            {
                'form': form,
                'post_id': post_id,
                'is_edit': is_edit
            }
        )

    form.save()
    return redirect('posts:post_detail', post_id)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends 'base.html' %}

{% block title %}
  {{  title  }}
{% endblock title %}

{% block content %}
  <div class="container py-5">
    <h1>{{  header  }}</h1>
    <p>{{  text  }}</p>
  </div>
{% endblock content %}

yatube/templates/about/tech.html
{% extends 'base.html' %}

{% block title %}
  {{  title  }}
{% endblock title %}

{% block content %}
  <div class="container py-5">
    <div class="row">
      <h1>{{  header  }}</h1>
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Python
          </li>
          <li class="list-group-item">
            Django
          </li>
        </ul>
      </aside>  
      <article class="col-12 col-md-9">
        <p>{{  text  }}</p>
      </article>
    </div>
  </div>
{% endblock content %}

yatube/templates/base.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>
    {% include 'includes/head.html' %}
  </head>
  <body>	   
    <header>
        {% include 'includes/nav.html' %}
    </header>
    <main>
        {% block content %}CONTENT{% endblock content %}
    </main>
      {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/head.html
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="/static/img/fav/fav.ico" type="image">
  <link rel="apple-touch-icon" sizes="180x180" href="/static/img/fav/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/static/img/fav/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/static/img/fav/favicon-16x16.png">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">
  <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  <title>
    {% block title %}TITLE{% endblock title %}
  </title>

yatube/templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="/static/img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>        
    <ul class="nav  nav-pills">
      <li class="nav-item">              
        <a class="nav-link" href="{% url 'about:author' %}">
          Об авторе
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about:tech' %}">
          Технологии
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'posts:post_create' %}">
          Новая запись
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light " href="../users/password_change_form.html">
          Изменить пароль
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
      </li>
      <li class="mt-2">
        Пользователь: {{  user  }}
      <li>
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url 'users:login' %}">
          Войти
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light " href="{% url 'users:signup' %}">Регистрация</a>
      </li>
    </ul>      
  </div>
</nav>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/includes/post_item.html
<article>
  <ul>
    <li>
      Автор: {{  post.author  }}
      <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{  post.pub_date |date:"D d M Y" }} 
    </li>
  </ul>
  <p>
    {{  post.text  }}
  </p>
<a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
</article>

{% if post.group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
{% endif %}

{% if not forloop.last %}<hr>{% endif %}  

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  {{  group.title  }}
{% endblock title %}

{% block content %}
      <div class="container py-5">        
        <h1>{{  group.title  }}</h1>
        <p>{{  group.description  }}</p>
        {% for post in page_obj %}
            {% include "includes/post_item.html" with post=post %}
        {% endfor %}
        {% if page_obj.has_other_pages %}
            {% include "includes/paginator.html" with page_obj=page_obj paginator=paginator%}
        {% endif %}
      </div>
      
{% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
  Последние обновления на сайте
{% endblock title %}

{% block content %}
      <div class="container py-5">        
        <h1>Все посты</h1>

        {% for post in page_obj %}
            {% include "includes/post_item.html" with post=post %}
            {% if not forloop.last %}<hr>{% endif %}  
        {% endfor %}

        {% if page_obj.has_other_pages %}
            {% include "includes/paginator.html" with page_obj=page_obj paginator=paginator%}
        {% endif %}
      </div>
      
{% endblock content %}

yatube/templates/posts/post_create.html
{% extends "base.html" %}

{% block title %} {% if is_edit %} Редактировать запись {% else %} Добавить запись {% endif %} {% endblock %}
{% block header %} {% if is_edit %} Редактировать запись {% else %} Добавить запись {% endif %} {% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Создать статью
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary btn-block">{% if is_edit %}Сохранить{% else %}Добавить запись{% endif %}</button>
          </div>
          </form>
        </div>
      </div>
    </div>
</div> 

{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
  {{  post.title  }}
{% endblock title %}

{% block content %}
<div class="container py-5">
        <div class="row">
          <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                Дата публикации: {{  post.pub_date |date:"D d M Y"  }}
              </li>               
              <li class="list-group-item">
                Группа: {{  post.group  }}
                <a href="{% url 'posts:group_list' post.group.slug %}">
                  все записи группы
                </a>
              </li>            
              <li class="list-group-item">
                Автор: {{  post.author  }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                Всего постов автора:  <span >{{ user.posts.all.count }}</span>
              </li>
              <li class="list-group-item">
                <a href="{% url 'posts:profile' post.author %}">
                  все посты пользователя
                </a>
              </li>
            </ul>
          </aside>
          <article class="col-12 col-md-9">
            <p>{{  post.text  }}</p>
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
              редактировать запись
            </a>                
          </article>
        </div>     
      </div>      
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{  user_obj  }}{% endblock title %}

{% block content %}
  <div class="container py-5">        
    <h1>Все посты пользователя {{  user_obj  }}</h1>
    <h3>Всего постов: {{  user_obj.posts.all.count  }}</h3> 
      {% for post in page_obj %}
            {% include "includes/post_item.html" with post=post %}
      {% endfor %}

      {% if page_obj.has_other_pages %}
            {% include "includes/paginator.html" with page_obj=page_obj paginator=paginator%}
      {% endif %}
  </div>
{% endblock content %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}

{% block title %}Вы вышли из системы{% endblock title %}

{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Выход</div>
          <div class="card-body"> <p>Вы вышли из своей учётной записи. Ждём вас снова!</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:signup' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

yatube/templates/users/password_change_done.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Пароль изменён</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="../posts/index.html">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
          <ul class="nav  nav-pills">
            <li class="nav-item">              
              <a class="nav-link" href="../about/author.html">
                Об авторе
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../about/tech.html">
                Технологии
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../posts/create_post.html">
                Новая запись
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/password_change_form.html">
                Изменить пароль
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/logged_out.html">Выйти</a>
            </li>
            <li>
              Пользователь: leo
            <li>
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/login.html">
                Войти
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/signup.html">Регистрация</a>
            </li>
          </ul>      
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>Пароль изменён успешно</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

yatube/templates/users/password_change_form.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Изменение пароля</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="../posts/index.html">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
          <ul class="nav  nav-pills">
            <li class="nav-item">              
              <a class="nav-link" href="../about/author.html">
                Об авторе
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../about/tech.html">
                Технологии
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../posts/create_post.html">
                Новая запись
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light active" href="../users/password_change_form.html">
                Изменить пароль
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/logged_out.html">Выйти</a>
            </li>
            <li>
              Пользователь: leo
            <li>
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/login.html">
                Войти
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/signup.html">Регистрация</a>
            </li>
          </ul>      
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post" action="../users/password_change_form.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Зарегистрироваться</div>
            <div class="card-body">

                {% for error in form.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error|escape }}
                </div>
                {% endfor %}

                <form method="post" action="{% url 'users:signup' %}">

                    {% csrf_token %}

                    {% for field in form %}
                    <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                    <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                        <div class="col-md-6">

                            {{ field|addclass:"form-control" }}

                            {% if field.help_text %}
                            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Зарегистрироваться
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}